version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: quanlythuctap_db
    restart: always
    environment:
      # CHỈNH TẠI ĐÂY: Khớp với ảnh phpMyAdmin của bạn
      MYSQL_DATABASE: quan_ly_thuc_tap 
      MYSQL_ROOT_PASSWORD: password123
      TZ: Asia/Ho_Chi_Minh
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: quanlythuctap_pma
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: password123
      TZ: Asia/Ho_Chi_Minh
    depends_on:
      - db

  web:
    build: .
    container_name: quanlythuctap_web
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www/html
    environment:
      TZ: Asia/Ho_Chi_Minh
    depends_on:
      - db